### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by hmkim** [NYU-Molecular-Pathology/NGS580-nf#8]
Hi!

Thank you for your code. (NGS580-nf).

When I try to build of Docker, I got the error in below.

```bash
$ git clone https://github.com/NYU-Molecular-Pathology/NGS580-nf.git
$ cd NGS580-nf/containers
$ make build-all-Docker
```

![2019-01-03 09 34 28](https://user-images.githubusercontent.com/4966343/50619162-f259c500-0f3a-11e9-8ae7-51b4043abb8f.png)

How can I solve this issue ? Please check this issue.

**Comment by stevekm** [comment]
Hi @hmkim , thanks for reporting this issue. I should preface this by noting that I have not actively worked on or used the Docker configs in a while, since my production system is running Singularity, so its possible that things have gotten out of date and I hadn't noticed. 

This is an error I have never seen before. Would you by chance know which Docker container caused it? It appears to be one of the ones that use `conda` with R packages, maybe one of the `variant-calling` or `R` or `reporting` containers?

From my experience building these containers with Docker and Singularity, I suspect there might be an issue with your hard disk configuration, especially in the amount of storage space available. On my Mac here, I have Docker configured for a 64GB Virtual disk image size, with 36GB used so far. I think this might be relevant because when system items mysteriously go missing like this inside the containers, it has often been due to the container silently running out of space. Singularity via Vagrant has been bad about this, though I would have expected Docker to throw a more explicit error if this were the case. 

<img width="612" alt="screen shot 2019-01-02 at 9 30 43 pm" src="https://user-images.githubusercontent.com/10505524/50621820-85144880-0ed6-11e9-80ab-b6e4d4ac9a41.png">

If you are able to, try checking on this config on your system, and increase it a bit if possible and try it again. If that does not fix it, then it would help to know which exact container is causing the issue, so try building them individually with the `make build-all-Docker VAR=container-dir-name` command until you hit the issue. 

I am running the full `make build-all-Docker` command right now on my desktop but it might take a while to finish.

**Comment by stevekm** [comment]
It looks like those are actually two different errors. The latter one appears to be a potential network error, since it was unable to source the BioConductor installer (via the internet). Not sure if network issues could have caused the first error though. You might simply keep trying it a few times and see if it gives the same errors repeatedly and/or starts working. However I saw that you have your location listed as Korea, and I think I did actually hard-code in the USA repo for CRAN in the `install.R` script there, so that might also make things difficult for you. 

I have uploaded an alternative version of this container, based on the current Singularity container. You can try it out by switching to the new branch:

```
git pull
git checkout deconstructSigs-fix
```

Let me know if this works better. Should be functionally identical to the old one but it installs everything from conda instead of CRAN and bioconductor.

**Comment by stevekm** [comment]
Also I was unable to replicate the errors you reported both with the new and old versions of that Docker container, they both build fine for me. So that also makes me wonder if it has something to do with either your system or your locality. Let me know if there are any updates.

**Comment by hmkim** [comment]
Really thank you for your thoughtful comment.

In fact, I had a problem of system disk. Maybe one issue  affected by this.

I'll try and report it. 

Have an nice day!

**Comment by hmkim** [comment]
After pull & checkout, I compiled successfully.

> $ git pull
> $ git checkout deconstructSigs-fix
> $ make docker-build VAR=deconstructSigs-1.8.0

Thank you!
